### ISSUE TITLE
WeTransfer yields InvalidTransfer

### ISSUE THREAD

**Issue by tsoernes** [fliot/py3wetransfer#4]
When I upload multiple files, py3wetransfer yields no error and prints a link. However,  WeTransfer is stuck at 'Preparing files' and when I click download it says 'Invalid request' or InvalidTransfer something of the sort, immediately followed by a message that the download period has expired.
https://i.imgur.com/7HbOt1p.png
WeTransfer says the problem is not on their end, and says that reasons for this issue might be that not all chunks of all files are uploaded, not all files are completed or finalized.

This issue does NOT happen when uploading the same files one by one.

**Comment by Sandyman** [comment]
Hi @tsoernes, 

When I first came across this repo a few weeks ago, I asked the owner whether it is still maintained. I haven't had a response as of yet, but I'm thinking it's not, unfortunately. 

I have taken the liberty of forking and reworking the entire project. Click on _the little number next to_ 'Fork' in the top right hand corner and click on the 'Sandyman' repository if you're interested in looking at the source. 

You can also download the package from pypi, it's called py3-wetransfer, so almost the same (just mind the extra dash). Just check the order of arguments for uploading a file or multiple files, because I changed that. It has tests, so I know that uploading multiple files works. 

I'd be more than happy to have the original owner (@fliot) integrate my changes, if and when possible. Until then, I'd suggest you use py3-wetransfer.

**Comment by tsoernes** [comment]
@Sandyman  Thanks. Did not have this issue with your fork.
